# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70a42b814f1a49914b661afcd05b14af4693374e65f3cb5809829e2f402719130d50b823c60325cf86799864c1384c5e4463eca87b17cee986934649555c37ed

test:
  secret_key_base: a3a038730760cd71da21f69052d62c2643ab90af9decb42141258757e0dc6dae41c56c92d977e85eb7d0f40d5585767152a7073c54fac264cdef26f92093e143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
